<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nb_vhs_assets_dependency_test"
 *
 * Auto generated by Extension Builder 2013-12-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'VHS assets dependency test',
	'description' => 'testing VHS assets dependency feature',
	'category' => 'plugin',
	'author' => 'Daniel Schöne',
	'author_email' => 'daniel@schoene.it',
	'author_company' => 'schoene.it',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'test',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>